---
title: "Obligatorio 8"
author: "Augusto Souto"
date: "5 de junio de 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




#Resumen: 

En el presente ejercicio se resumirá el paper "Investment Uncertainty Analysis in Eucaliptus Bole Biomass Production in Brazil". 

##Objetivo
El paper tiene como objetivo el análisis de la rentabilidad financiera de 5 prácticas de plantación distintas de plantación (con un horizonte de 36 meses) de Eucalyptus en el estado de Sao Paulo en Brasil. Para esto, se proponen una serie de indicadores de performance financierta que miden el desempeño de las siguientes prácticas, que están determinadas por el espaciado que tienen entre sí las hileras de eucalyptus y por el espacio que tienen los árboles plantados entre sí. El primer tipo de prácticas supone 3 metros entre hileras y 2 entre los árboles, el segundo 3 metros entre hileras y 1 entre árboles, el tercero 1.5 metros entre hileras y 2 metros entre árboles, el cuarto 3 metros entre hileras y 0.5 metros entre árboles y el quinto 1.5 metros entre hileras y 1 metro entre árboles.

##Metodos

Para medir el desempeño financiero de este tipo de prácticas, se proponen diferentes indicadores, como el valor presente neto, la tasa única de retorno y el índice de rentabilidad. La primer métrica mide un flujo de ingresos actualizados al presente mediante la aplicación de una tasa de interés, que refleja el costo del capital, menos el costo de la inversión al momento de ejecutarla. La segunda métrica nos da una tasa de retorno calculada a partir de los flujos de ingresos, una tasa de reinversión de los mismos, los flujos de egresos y una tasa de financiamiento de los mismos. Por último, el indice de rentabilidad expresa un ratio entre el valor presente de los flujos de ingresos y el valor de la inversión, por lo que expresa una relación de costo-beneficio. 

La estrategia de investigación del trabajo consiste en investigar como influyen ciertas variables en el resultado financiero del proyecto, medido por la mencionadas métricas,. Las variables a investigar son  la biomasa del tronco (medida en toneladas por hectarea), los costos de aplicación de las medidas (medida en dolares por hectarea), costos de tratamiento silvicola (medida en dolares por hectarea), costos de administración (medida en dolares por hectarea) y costos de la renta de la tierra (medida en dolares por hectarea). Para llevar a cabo esta investigación se aplica un analisis de monte carlo, suponiendo que tales variables son aleatorias y siguen una distribución triangular, con una variación de mas o menos 15\% alrededor de la moda. La moda de estas variables fue determinada en base al criterio de expertos.

Por otro lado, la estrategia calibra la tasa de retorno mínima (requerida para que el proyecto se lleve a cabo) mediante datos empíricos. En paricular, la misma se determina mediante un modelo de valoración de activos (CAPM). Este tipo de enfoque tiene la ventaja de considerar el riesgo inherente al sector y al país en el cual se desarrolla la actividad.

##Resultados

Los resultados del trabajo, dados una vez que se hacen las simulaciones, muestran el rendimiento en términos de biomasa forestal, de los diferentes costos, de la tasa de retorno única y del indice de rentabilidad. En primer lugar, se halla que, como es de esperar, las estrategias que suponen menos espaciamiento entre árboles, producirán más biomasa forestal. En segundo lugar, se muestra que las estrategias más intensivas tienen la desventaja de ser más costosas en términos de sus costos de aplicación. Este último factor genera que, cuando se muestrea la  funciones de distribución de la tasa única de retorno, solo las prácticas 1 y 2 tienen una probabilidad alta de obtener una tasa mayor a la tasa de referencia (13.8\%). La práctica 3 tiene una alta probabilidad de generar un retorno positivo pero menor al de la tasa de referencia mientras que en los casos de las prácticas 4 y 5, además de dar retornos menores a los de tal tasa, generan valores presentes netos negativos, lo que se explica por el alto diferencial de costos que estas prácticas conllevan. En los resultados del indice de rentabilidad ocurre algo muy parecido, dado que solo las prácticas 1 y 2 tienen un  ratio, en moda, mayor a 1, lo que significa que generan más valor de lo que cuestan. 

Por último, se estudió la relación de las variables con los rendimientos financieros mediante el coeficiene de correlación de Spearman. En tal análisis se halla que el precio de la biomasa forestal es la variable que está más correlacionada con el valor presente neto del proyecto. A esta variable le siguen en importancia, dependiendo del escenario considerado, la producción de biomasa y los costos de aplicación.

##Observaciones

La debilidad más grande del análisis, según se entiende, estaría en no tener datos estadísticos sobre que permitan calibrar de manera más precisa la naturaleza de las variables a simular. Sin embargo, también esto podría deberse mas que nada a una deficiencia de los sistemas de información y no al diseño de la estrategia empírica propuesta por los autores.








